<?php
// src/OC/UserBundle/Repository/UserRepository.php

namespace OC\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeurRepository extends \Doctrine\ORM\EntityRepository
{
	function getUserType (){
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.id != :id')
				->setParameter('id', '3');
		return $qb;
	}
}
