# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

  encoders:
    OC\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_USER:		ROLE_USER
    ROLE_ADMIN:       ROLE_ADMIN
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
        id: fos_user.user_provider.username_email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main_login:
        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
        pattern:   ^/login$
        anonymous: true # On autorise alors les anonymes sur ce pare-feu  
    main: 
      pattern:   ^/
      anonymous: true
      provider:  main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        always_use_default_target_path : true
        default_target_path: /User/MaPage
        use_referer : true
      logout:
        path:       fos_user_security_logout
        target:     /
      remember_me:
        secret:     %secret%
        
  access_control:
      - { path: ^/Admin, roles: ROLE_USER }
      - { path: ^/User, roles:  ROLE_USER }