# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    security.exception_listener.class: OC\PlatformBundle\Security\Firewall\ExceptionListener

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    hello_service:
        class: OC\UserBundle\Services\HelloService
        arguments: ['@mailer']
    
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
        
    rs_user.registration_complet:
        class: OC\UserBundle\Services\RegistrationConfirmListener
        arguments: ['@router']
        tags: 
            - { name: kernel.event_subscriber }
            
        