<?php
// src/OC/PlatformBundle/Repository/AnnonceSiteemploiRepository.php

namespace OC\PlatformBundle\Repository;

/**
 * AnnonceSiteemploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceSiteemploiRepository extends \Doctrine\ORM\EntityRepository
{
	function getListeSite($id){
			$qb = $this->createQueryBuilder('a');
			$qb
				->where('a.idAnnonce = :id')
				->setParameter('id', $id);

			return $qb->getQuery()
					->getResult();
		}
}
?>