<?php
// src/OC/PlatformBundle/Repository/CandidatRepository.php

namespace OC\PlatformBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
	function getCandidat()
	{
		$qb = $this->createQueryBuilder('a');
		$qb 
			->orderBy('a.datecreation','DESC')
			;
		
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getCVTheque()
	{
		$qb = $this->createQueryBuilder('a');
		$qb 
			->orderBy('a.nom','ASC')
			;
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getCVThequeTrie($site,$dept)
	{
		$qb = $this->createQueryBuilder('a');
		$qb 
			->orderBy('a.nom','ASC')
			->join('a.annonce','annonce')
				;
			
			if($site != null && $dept != null){
				$qb->join('annonce.site','s')
					->join('s.idSiteemploi','site')
					->where('site.id = :ss')	
					->setParameter('ss', $site)
					->join('a.codePostal','v')
					->join('v.departement','d')
					->AndWhere('d.id = :dept')
					->setParameter('dept', $dept);
			}else{
				if($site != null){
				$qb->join('annonce.site','s')
					->join('s.idSiteemploi','site')
					->where('site.id = :ss')	
					->setParameter('ss', $site);
				}

				if($dept != null){
					$qb->join('a.codePostal','v')
						->join('v.departement','d')
						->where('d.id = :dept')
						->setParameter('dept', $dept);
				}
			}
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getCandidatCandidature($id)
	{
		$qb = $this->createQueryBuilder('a');
		$qb 
			->where('a.idCandidat = :id')
				->setParameter('id', $id)
			;
		
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getCandidatFonction($candidat,$fonction){
		$qb = $this->createQueryBuilder('c');
		$qb 
			->where('c.id = :id')
			->setParameter('id', $candidat)
			->join('c.fonction','f')
			->andWhere('f.id = :fonction')
			->setParameter('fonction', $fonction)	
			;
		
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getCandidatTri($site,$departement,$fonction){
		$qb = $this->createQueryBuilder('c');
		$qb->orderBy('c.nomcandidat','ASC');
			if ($site != null){
				$qb ->where('c.site = :site')
				->setParameter('site', $site);
			}
			if ($departement != null){
				$qb->andWhere('c.Departement = :departement')
				->setParameter('departement', $departement);	
			}
			
			if($fonction != null){
				$qb->join('c.fonction','fonction')
					->andWhere('fonction.intitulefonction = :f')
				->setParameter('f', $fonction);	
			}
			
			;
		
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	//Fonction pour compter le nombre de reponse dans les anciennes annonces
	function getNbAnnonce($id){
		$qb = $this->createQueryBuilder('a');
		$qb ->select('count(a.id)')
			->join('a.annonce', 'e')
			->where	('e.id = :id')
			->setParameter('id', $id);
		
		return $qb->getQuery()
				->getSingleScalarResult();
	}
	
	//Récupération des candidats selon une fonction
	function getCVThequeByFonction($id){
		$qb = $this->createQueryBuilder('c');
		$qb->orderBy('c.nom','ASC')
			->join('c.annonce','a')
			->join('a.site','s')
			->where('s.idFonction = :id')
			->setParameter('id', $id);
		
		return $qb
				->getQuery()->getResult();
				
	}
	
	
}

?>