<?php
// src/OC/PlatformBundle/Repository/RecruteurRepository.php

namespace OC\PlatformBundle\Repository;

/**
 * RecruteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruteurRepository extends \Doctrine\ORM\EntityRepository
{
	function getAnnonce($utilisateur){
		$qb = $this->createQueryBuilder('a');
		$qb 
			->where('a.id = :id')
			->setParameter('id', $utilisateur)
			->join('a.annonce','ann')
			->addSelect('ann')	
			->orderBy('ann.datecreation',DESC)
			->setMaxResults(5)
			;
		
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getRecruteurByEmail($mail){
		$qb = $this->createQueryBuilder('a');
		$qb 
			->join('a.user','u')	
			->where('u.email = :mail')
			->setParameter('mail', $mail)
			;
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getPremium(){
		$qb = $this->createQueryBuilder('a');
		$qb ->join('a.premium','p')
			->where('p.dateFin <= :date')
			->setParameter('date', new \DateTime('now'));
		
		return $qb
				->getQuery()
				->getResult();
	}
}
?>