<?php
// src/OC/PlatformBundle/Repository/VilleRepository.php

namespace OC\PlatformBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{
	function getByCp($cp){
		$qb = $this->createQueryBuilder('a');
		$qb 
			->where('a.codePostal = :cp')
			->setParameter('cp', $cp)
			->setMaxResults(1);	
			
		
		
		return $qb->getQuery()->getResult();
				
	}
	
	
}
?>